services:
  instabug-db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: chat_system
      MYSQL_USER: instabug
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - instabug-network

  instabug-redis:
    image: redis:latest
    container_name: instabug-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "6380:6379"
    networks:
      - instabug-network

  instabug-rabbitmq:
    image: rabbitmq:3-management
    container_name: instabug-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - instabug-network
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status" ]
        interval: 10s
        timeout: 5s
        retries: 5

  instabug-chat:
    build:
      context: .
    expose:
      - "3000"
    restart: always
    depends_on:
      - instabug-db
      - instabug-redis
      - elasticsearch
      - instabug-rabbitmq
    networks:
      - instabug-network

  instabug-nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - instabug-chat
    networks:
      - instabug-network

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: instabug-elasticsearch
    environment:
      - cluster.routing.allocation.disk.watermark.low=600mb
      - cluster.routing.allocation.disk.watermark.high=500mb
      - cluster.routing.allocation.disk.watermark.flood_stage=200mb
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTIC_PASSWORD=password123
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Limit memory usage
    ports:
      - "9200:9200"  # REST API
      - "9300:9300"  # Node communication
    networks:
      - instabug-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  instabug-network:
    name: instabug-network
